---
title: "Test Scores"
author: "Thomas Gow"
date: "11/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Test Score PCA Example


```{r cars}
data <- read.csv('/Users/thomasgow/Documents/IAA/Fall1_IAA/Linear Algebra/PCA/testscores.csv')

head(data)
```


```{r}
pca <- prcomp(data, scale =T)
```


To get the screeplot:
```{r}
plot(pca$sdev^2, type='b', ylab = 'Eigenvalue (Variance of Each Component)', main = 'Starwars Screeplot')
```



## Projection of data in 2 dimensions:  

```{r}
plot(pca$x[,1:2], main='Projection of the 1186 Survey Respondents \n in 2-dimensional space')
```


```{r}
plot(jitter(pca$x[,1:2],amount=0.1), main='Projection of the 1186 Survey Respondents \n in 2-dimensional space (w/Jitter)')
```



Below the numbers of PCA 1 and PCA 2 loadings.


```{r}
tail(pca$rotation[order(abs(pca$rotation[,1])),1],10)

```



```{r}
pcaOut <- prcomp(data,3, scale = F)
plot(pcaOut$x[,1],pcaOut$x[,2],col = cancerlabels$Class, xlab = "Principal Component 1", ylab = "Principal Component 2", main = 'Genetic Samples Projected into 2-dimensions')
```



```{r}
biplot(pca, main = 'BiPlot: The observations and variables projected onto the same plane.',cex = c(1, .8))

```

